### ISSUE TITLE
not support viewport units: vh and vw

### ISSUE THREAD

**Issue by springuper** [closingtag/calc-polyfill#30]
I wanna use this polyfill to fix vh/vw not working in old safari, here is a demo: https://codepen.io/mherchel/pen/mIueA. But it doesn't work. Do you have any plan to support it?

**Comment by rodebert** [comment]
As far as I can see there is no Safari Version that does support viewport units and not `calc`.

http://caniuse.com/#feat=calc
http://caniuse.com/#feat=viewport-units

Both CSS Features are supported since Safari-Version 6 and 6.1 for iOS.

Additionally it is not the intend of this polyfill to add support for viewport units for browsers lacking this.
